import type {Content,Entry} from '../lib/content';
import RichArticle,{type ArticleNode} from './RichArticle';
const text=(nodes:ArticleNode[]):string=>nodes.map(n=>n.text||text(n.children||[])).join(' ');
export default function ArticleView({content:c,related}:{content:Content;related:Entry[]}){
 const nodes:ArticleNode[]=[];
 for(const node of c.body_nodes||[]){const first=node.children?.[0];if(node.type==='paragraph'&&first?.bold&&/[:：]$/.test(first.text?.trim()||'')){nodes.push({type:'heading',level:2,children:[{type:'text',text:first.text?.replace(/[:：]$/,'')}]},{...node,children:node.children?.slice(1)});}else nodes.push({...node});}
 let count=0;for(const n of nodes)if(n.type==='heading')n.anchor='article-section-'+(++count);
 const headings=nodes.filter(n=>n.type==='heading');const words=text(nodes).split(/\s+/).filter(Boolean).length;const minutes=Math.max(1,Math.ceil(words/200));
 const date=(value:string)=>new Date(value).toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'});
 return <article className="article-reading"><header><div className="article-meta"><a href="#article-author">By {c.author_name||'Nura Interiors'}</a><span> · {minutes} min read</span>{c.published_date?<span> · Published <time dateTime={c.published_date}>{date(c.published_date)}</time></span>:null}{c.modified_date?<span> · Updated <time dateTime={c.modified_date}>{date(c.modified_date)}</time></span>:null}</div><p className="article-deck">{c.seo_description||c.summary}</p></header>{words>=500&&headings.length>=4?<nav className="article-toc" aria-label="On this page"><h2>On this page</h2><ol>{headings.map(n=><li key={n.anchor}><a href={'#'+n.anchor}>{text(n.children||[])}</a></li>)}</ol></nav>:null}<div className="article-content">{nodes.length?<RichArticle nodes={nodes}/>:c.body?.split(/\n\s*\n/).map((p,i)=><p key={i}>{p}</p>)}</div><aside id="article-author" className="article-author"><h2>About the author</h2><p><strong>{c.author_name||'Nura Interiors'}</strong> is the credited author of this article in the Nura journal.</p><a href="/about">About Nura Interiors</a></aside>{related.length?<nav className="article-related" aria-label="Related articles"><h2>Continue reading</h2><ul>{related.map(e=><li key={e.path}><a href={e.path}>{e.content.title}</a></li>)}</ul></nav>:null}<div className="article-next"><h2>Considering a kitchen project?</h2><p>Discuss your layout, materials and practical requirements with the Nura studio.</p><a className="text-link" href="/consultation">Request a design consultation <span>↗</span></a></div></article>;
}
