import ArticleScrollMarker from './ArticleScrollMarker';
import RelatedArticles from './RelatedArticles';
import type {Content,Entry} from '../lib/content';
import RichArticle,{type ArticleNode} from './RichArticle';
const text=(nodes:ArticleNode[]):string=>nodes.map(n=>n.text||text(n.children||[])).join(' ');
export default function ArticleView({content:c,related}:{content:Content;related:Entry[]}){
 const nodes:ArticleNode[]=[];
 let earlyCta:ArticleNode|undefined;
 for(const node of c.body_nodes||[]){if(node.type==='cta'&&node.cta==='article-early-consultation'){earlyCta=node;continue;}const first=node.children?.[0];if(node.type==='paragraph'&&first?.bold&&/[:：]$/.test(first.text?.trim()||'')){nodes.push({type:'heading',level:2,children:[{type:'text',text:first.text?.replace(/[:：]$/,'')}]},{...node,children:node.children?.slice(1)});}else nodes.push({...node});}
 let count=0;for(const n of nodes)if(n.type==='heading')n.anchor='article-section-'+(++count);
 const headings=nodes.filter(n=>n.type==='heading');const words=text(nodes).split(/\s+/).filter(Boolean).length;const minutes=Math.max(1,Math.ceil(words/200));
 const hasSidebar=words>=500&&headings.length>=4;
 const sectionHeadings=headings.filter(n=>(n.level||2)===2);
 const labels:Record<string,string>={'The project at a glance':'Project overview','The brief: a kitchen with real impact':'The client brief','From a catalogue reference to a design for the home':'Developing the design','Selecting the porcelain slabs in Italy':'Slab selection','Engineering the island: appearance, weight and movement':'Engineering the island','Manufacturing and assembly in Italy':'Manufacture in Italy','Delivering the assembled island to Amersham Road':'Delivery and access','The finished kitchen: a connected material palette':'The finished kitchen','What this project shows about bespoke kitchen design':'Design lessons','Questions about the porcelain island':'Questions and answers','Planning your own kitchen or island':'Planning your project','Project credits and sources':'Credits and sources'};
 const tocLinks=sectionHeadings.map(n=><li key={n.anchor}><a href={'#'+n.anchor}>{labels[text(n.children||[])]||text(n.children||[])}</a></li>);
 const date=(value:string)=>new Date(value).toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'});
 return <article className={"article-reading"+(hasSidebar?" article-reading-with-sidebar":"")}>{hasSidebar?<ArticleScrollMarker/>:null}<header><div className="article-meta"><a href="https://www.linkedin.com/in/joanne-h/" target="_blank" rel="noopener noreferrer">By {c.author_name||'Nura Interiors'}</a><span> · {minutes} min read</span>{c.published_date?<span> · Published <time dateTime={c.published_date}>{date(c.published_date)}</time></span>:null}{c.modified_date?<span> · Updated <time dateTime={c.modified_date}>{date(c.modified_date)}</time></span>:null}</div><p className="article-deck">{c.seo_description||c.summary}</p></header>{earlyCta?<RichArticle nodes={[earlyCta]}/>:null}<div className="article-reading-layout">{hasSidebar?<aside className="article-reading-sidebar"><div className="article-sidebar-inner"><nav className="article-toc" aria-label="On this page"><h2>On this page</h2><ol>{tocLinks}</ol></nav><details className="article-toc-mobile"><summary>On this page <span>View sections</span></summary><nav aria-label="Article sections"><ol>{tocLinks}</ol></nav></details><div className="article-sidebar-guide"><p className="eyebrow">Plan your project</p><a href={/^(Bespoke Kitchens|Bespoke Joinery)/.test(c.title)?'/london':'/guides/bespoke-kitchens'}>{/^(Bespoke Kitchens|Bespoke Joinery)/.test(c.title)?'Arrange a Fulham showroom conversation':'Explore the bespoke kitchen guide'} <span aria-hidden="true">↗</span></a><p>Layout, materials and the steps from brief to installation.</p></div></div></aside>:null}<div className="article-content">{nodes.length?<RichArticle nodes={nodes}/>:c.body?.split(/\n\s*\n/).map((p,i)=><p key={i}>{p}</p>)}</div></div><div className="article-reading-footer"><aside id="article-author" className="article-author"><h2>About the author</h2><p><strong><a href="https://www.linkedin.com/in/joanne-h/" target="_blank" rel="noopener noreferrer">{c.author_name||'Nura Interiors'}</a></strong> writes for the Nura journal. Explore her professional profile on LinkedIn.</p><a href="/about">About Nura Interiors</a></aside><RelatedArticles entries={related}/><div className="article-next"><h2>{c.title.startsWith('Bespoke Joinery')?'Considering a joinery project?':'Considering a kitchen project?'}</h2><p>Discuss your layout, materials and practical requirements with the Nura studio.</p><a className="text-link" href="/consultation">Request a design consultation <span>↗</span></a></div></div></article>;
}
