import ImageLicense from './ImageLicense';
import Image from 'next/image';
import assetMap from '../lib/asset-map.json';
const imageSource=(filename:string)=>(assetMap as Record<string,string>)[filename]||filename;
import type {Asset,Entry} from '../lib/content';
export function Photo({asset,priority=false,className='',fallbackAlt='',sizes='(max-width:800px) 100vw, 50vw'}:{asset?:Asset;priority?:boolean;className?:string;fallbackAlt?:string;sizes?:string}){return asset?.filename?<div className={'inner-photo '+className}><ImageLicense asset={asset} name={fallbackAlt}/><Image src={imageSource(asset.filename)} alt={asset.alt||fallbackAlt} fill sizes={sizes} priority={priority}/></div>:null;}
export function Hero({title,kicker,asset,summary,cta}:{title:string;kicker:string;asset?:Asset;summary?:string;cta?:{href:string;label:string}}){const words=title.split(' '),last=words.pop();return <section className="hero inner-hero">{asset?.filename?<><ImageLicense asset={asset} name={title}/><Image className="hero-image" src={imageSource(asset.filename)} alt={asset.alt||title} fill sizes="100vw" priority/></>:<div className="inner-hero-solid"/>}<div className="hero-shade"/><div className="hero-copy"><p className="eyebrow">{kicker}</p><h1>{words.join(' ')}{words.length>0?' ':''}<em>{last}</em></h1>{summary?<p className="hero-lede">{summary}</p>:null}</div><div className="hero-foot"><a href={cta?.href||"/projects"}>{cta?.label||"Explore the collection ↘"}</a><span>Nura Interiors</span></div></section>;}
export function Card({entry,index=0}:{entry:Entry;index?:number}){const c=entry.content;return <a className={'project-card inner-project-card'+(index===0?' project-card-tall':'')} href={entry.path}><Photo asset={c.hero} fallbackAlt={c.title}/><span className="project-meta"><small>{c.location||c.category}</small><b>{c.title}</b><i>Explore {c.component==='article'?'the story':'the project'} ↗</i></span></a>;}
export function Cta(){return <section className="contact section-pad"><div className="section-kicker">Start your project</div><div className="contact-grid"><h2>Make room for<br/><em>what matters.</em></h2><div><p>Tell us about your home and we’ll start a conversation.</p><a className="button" href="/#contact">Enquire with Nura <span>↗</span></a></div></div></section>;}
