import {Photo} from './Editorial';
import '../app/joinery.css';

export default function JoineryContent(){return <div className="service-detail joinery-content">
 <section><p className="eyebrow">Made for the room</p><h2>Bespoke joinery, from one room to a connected home.</h2><p>Plan fitted furniture around what the space needs to do. Nura works with homeowners, architects and interior designers on cabinetry, storage and architectural details. Start with the rooms, daily routines and design intent; then develop the materials and technical requirements together.</p><a className="text-link" href="/consultation">Discuss your joinery brief ↗</a></section>
 <section><h2>What would you like the space to do?</h2><h3>Libraries, shelving and alcove storage</h3><p>Consider the objects you want to display, the items you need to conceal and the proportions of the room. Shelf spans, loading, door clearances and access to sockets belong in the brief alongside the finish.</p><h3>Media furniture and integrated cabinetry</h3><p>Bring equipment dimensions, ventilation requirements, cable routes and maintenance access into the discussion early. The joinery needs to accommodate the equipment and the surrounding architecture, rather than hide unresolved technical decisions.</p><h3>Wardrobes and dressing rooms</h3><p>Plan hanging space, drawers, shelving and circulation around your routine. Discuss internal fittings, door movement and lighting together.</p><a href="/services/wardrobes-dressing-rooms">Explore bespoke wardrobes and dressing rooms ↗</a><h3>Joinery across several rooms</h3><p>Identify which materials and details should carry through the home, and where each room needs a different response. A shared palette can connect spaces while keeping their practical requirements distinct.</p></section>
 <section><h2>See the material decisions in real projects.</h2><figure><Photo asset={{filename:'/assets/archive/a4d6c0bea134eb76-local.webp',alt:'Timber shelving and recessed lighting in Nura’s Westover Road joinery project'}} sizes="(max-width:800px) 100vw, 50vw"/><figcaption>Westover Road, Wandsworth: timber shelving and lighting detail.</figcaption></figure><h3>Westover Road</h3><p>The project specification combines whitewashed oak veneer, recessed lighting and Calacatta Cremo marble. Explore the photographs to see how timber, stone and light are brought into the fitted interior.</p><a href="/joinery/westover-road">Explore Westover Road joinery ↗</a><h3>Akehurt Street</h3><p>The published specification brings together an off-white matt lacquer finish, walnut interiors, glazed doors and carved handles. It is another reference for discussing the relationship between the outside finish, internal materials and door details.</p><a href="/jointery/akehurt-street">Explore Akehurt Street joinery ↗</a><p>These are material references from individual projects. Your specification and scope will be developed for your home.</p></section>
 <section><h2>Resolve the junctions before manufacture.</h2><ul><li><strong>Survey and fit:</strong> confirm dimensions, wall conditions, skirting, ceiling junctions and installation access.</li><li><strong>Materials and hardware:</strong> review samples, grain direction, edges, handles, hinges and internal fittings.</li><li><strong>Lighting and services:</strong> coordinate equipment, ventilation, cable access and responsibilities with the relevant trades.</li><li><strong>Delivery and handover:</strong> agree the installation scope, site readiness, protection, snagging and care information.</li></ul><p>For architects and designers, share drawings, specifications and the project stage. Identify the decisions already approved and the details that still need development. Responsibilities and deliverables should be agreed for the appointment.</p><a href="/for-professionals">Working with Nura as an architect or designer ↗</a></section>
 <section><h2>Before the first conversation.</h2><h3>What should I send?</h3><p>Your property location, the rooms involved, available plans or photographs, material references and an approximate budget and target dates. Highlight access constraints and any equipment that needs integration. Drawings can be shared with studio@nura-interiors.com.</p><h3>How much does bespoke joinery cost?</h3><p>Dimensions, construction, finishes, hardware and installation requirements affect the quotation. A single cabinet and a whole-home commission have different scopes. Ask for the inclusions, exclusions and applicable VAT to be set out in your proposal.</p><h3>How long will it take?</h3><p>The programme depends on the approved specification, production requirements and site readiness. Confirm the stages and responsibilities with the studio against your actual brief.</p><h3>Can I discuss samples in person?</h3><p>Contact the Fulham studio at 367 Fulham Palace Road, London SW6 6TA to arrange a visit before travelling.</p><a href="/london">Plan a Fulham showroom visit ↗</a><p><a href="/guides/bespoke-joinery-london">Read the bespoke joinery planning guide ↗</a></p><a className="button" href="/consultation">Discuss your joinery project ↗</a></section>
</div>;}
