import '../app/process.css';

const stages=[
 {title:'Share the brief',output:'A shared outline of the rooms, priorities, location, budget and target dates to discuss.',studio:'Review the information provided and identify the questions needed to develop the scope.',client:'Share available plans, photographs and references. Introduce your architect or designer, if appointed.',check:'Confirm the proposed next step and any further information required.'},
 {title:'Develop the design',output:'A layout and material direction for discussion, with the design deliverables agreed for your appointment.',studio:'Develop the agreed design scope and explain the practical implications of material and storage choices.',client:'Review the proposals, bring together feedback and identify the decisions that need approval.',check:'Agree the design direction, inclusions, exclusions and how revisions will be handled.'},
 {title:'Resolve the technical details',output:'The dimensions, specification and coordination information required for the agreed work.',studio:'Coordinate the joinery requirements and identify interfaces with lighting, appliances, surfaces and the building.',client:'Help arrange access and decisions with the relevant design team and trades. Confirm who provides the measured information.',check:'Identify who checks and approves dimensions, finishes and technical information before manufacture.'},
 {title:'Agree the order and programme',output:'A project-specific quotation, scope, programme and commercial terms to review.',studio:'Set out the agreed scope and discuss manufacture, delivery and installation requirements.',client:'Review the written proposal and confirm the agreed approvals and site preparations.',check:'Confirm applicable VAT, payment stages, exclusions and the procedure for changes in writing.'},
 {title:'Coordinate manufacture and installation',output:'Agreed delivery arrangements, site readiness requirements and installation responsibilities.',studio:'Coordinate the work within the agreed appointment and communicate the requirements affecting delivery and fitting.',client:'Arrange access and readiness with your contractor and other trades, including services and protection where assigned to them.',check:'Confirm the installation sequence, trade interfaces and any changes affecting cost or timing.'},
 {title:'Review the completed work',output:'An agreed completion review, any outstanding items and relevant care information.',studio:'Discuss the completed scope, identify items requiring attention and explain the agreed follow-up.',client:'Review the work with the team and raise questions about operation, finish and care.',check:'Confirm the completion record, responsibility for outstanding items and the appropriate aftercare contact.'}
];

export default function ProcessContent(){return <div className="process-content service-detail">
 <section><p className="eyebrow">Know what comes next</p><h2>From your brief to the finished space.</h2><p>A kitchen or joinery project involves design decisions, technical information and several people working together. Use the stages below to understand what needs to be discussed and agreed. The exact deliverables, responsibilities and sequence depend on your appointment and written proposal.</p><nav aria-label="Process stages"><ol>{stages.map((s,i)=><li key={s.title}><a href={'#process-stage-'+(i+1)}>{s.title}</a></li>)}</ol></nav></section>
 {stages.map((s,i)=><section key={s.title} id={'process-stage-'+(i+1)}><p className="eyebrow">Stage {i+1}</p><h2>{s.title}</h2><p className="process-output"><strong>What to agree:</strong> {s.output}</p><dl><dt>The studio</dt><dd>{s.studio}</dd><dt>You and your project team</dt><dd>{s.client}</dd><dt>Before moving forward</dt><dd>{s.check}</dd></dl></section>)}
 <section><h2>Clear expectations before you commit.</h2><h3>How long will the project take?</h3><p>Ask for a programme against your brief. Design approvals, material availability, manufacturing requirements, access and site readiness affect the dates. A change to dimensions, finishes or appliances may affect later stages.</p><h3>What is included in the quotation?</h3><p>Check the scope of design, cabinetry, surfaces, appliances, delivery, installation and work by other trades. Confirm exclusions, VAT treatment, payment stages and how variations are approved. There is no universal payment schedule or fixed lead time published here.</p><h3>Who coordinates with my architect or builder?</h3><p>Agree the point of contact and responsibility for each interface before work begins. Share the current drawings and project stage so the studio can discuss the coordination required.</p><a href="/for-professionals">Information for architects and designers ↗</a></section>
 <section><h2>A useful first conversation.</h2><p>Bring your property location, available plans or photographs, the rooms involved, references, approximate budget and target dates. You do not need every decision resolved before contacting the studio.</p><p><a href="/london">Arrange a Fulham showroom visit ↗</a></p><a className="button" href="/consultation">Discuss your project ↗</a></section>
</div>;}
