type Section={title:string;body:string;links?:{label:string;href:string}[]};
const sections:Record<string,Section[]>={
 '/services/bespoke-kitchens':[
  {title:'Plan your bespoke kitchen',body:'Use our kitchen planning guide to compare layout, materials, scope and installation responsibilities before developing your brief.',links:[{label:'Bespoke kitchen planning guide',href:'/guides/bespoke-kitchens'}]},
  {title:'Start with the way you use your kitchen',body:'Tell us how you cook, entertain and move through the room. Share the property location, available drawings, appliance requirements and any references that explain the materials or atmosphere you have in mind. A useful brief brings practical priorities and design direction together.'},
  {title:'Layout, materials and cabinetry',body:'Consider the relationship between cabinetry, the island, storage, worktops and the rest of the home. Material decisions also affect maintenance, durability and detailing. Explore our projects to see different approaches to timber, stone, finishes and integrated storage.',links:[{label:'Elm Park Road kitchen',href:'/kitchens/elm-park-road'},{label:'Tansley Farm kitchen',href:'/kitchens/tansley-farm'},{label:'Worktop ideas',href:'/inspiration/worktops'}]},
  {title:'Discuss scope and budget early',body:'The size of the room, cabinetry specification, worktops, appliances and installation requirements affect the scope of a kitchen project. Share an approximate budget and target timeline so the studio can discuss the next step. Project costs and programme need to be confirmed against your brief; there is no single price or lead time for every bespoke kitchen.',links:[{label:'Our design process',href:'/process'},{label:'Arrange a consultation',href:'/consultation'}]}
 ],
 '/services/architectural-joinery':[
  {title:'Furniture that belongs to the architecture',body:'Architectural joinery brings fitted storage, shelving, libraries and media furniture into the design of a home. Consider how each piece meets walls, floors, lighting and adjacent materials. The brief should describe both the intended appearance and the practical use of the space.'},
  {title:'Bring the drawings and the design intent',body:'If you are working with an architect or interior designer, share the available drawings, specifications and project stage. Identify the rooms, finishes and interfaces that need development. The studio can discuss the joinery scope, material options and coordination requirements with your design team.',links:[{label:'For architects and designers',href:'/for-professionals'},{label:'Westover Road joinery',href:'/jointery/westover-road'}]},
  {title:'Resolve the details before committing',body:'Access, room dimensions, hardware, services and installation conditions influence the specification and programme. Raise these requirements at the first discussion and ask the studio to confirm the responsibilities and deliverables for your project. Share a budget range and target dates alongside the drawings.',links:[{label:'Joinery inspiration',href:'/inspiration/joinery'},{label:'Discuss your project',href:'/consultation'}]}
 ],
 '/services/wardrobes-dressing-rooms':[
  {title:'Plan storage around your routine',body:'Start with what you need to store: hanging garments, folded clothing, shoes, accessories and luggage. Consider how often each item is used and whether storage should be open, behind doors or a combination of both. Available wall space and circulation determine how the room can work.'},
  {title:'Bring the whole room into the brief',body:'Share the layout, ceiling height, windows, doors and any existing electrical or lighting positions. Materials, handles, internal fittings and lighting should be considered together. If other joinery is being developed for the home, explain the intended relationship between the rooms.'},
  {title:'Prepare for the first conversation',body:'Send drawings or measured information where available, a few references and an indication of budget and timing. The studio can discuss the scope and the information required to develop it. Specification, price and installation programme are confirmed for the individual project.',links:[{label:'Architectural joinery',href:'/services/architectural-joinery'},{label:'Storage inspiration',href:'/inspiration/storage'},{label:'Arrange a consultation',href:'/consultation'}]}
 ],
 '/services/living-spaces':[
  {title:'Libraries, media furniture and fitted storage',body:'Living-space joinery should balance display, storage and the proportions of the room. Think about books, objects, equipment and everyday items, and decide what should be visible. The way the space is used provides the starting point for the design brief.'},
  {title:'Coordinate lighting, equipment and materials',body:'Share requirements for screens, speakers, cable routes and ventilation with the studio. Note any existing services and the intended lighting approach. Timber, painted finishes, stone and hardware influence both the appearance and the detailing of fitted furniture.'},
  {title:'Discuss a connected design direction',body:'If your project includes a kitchen or other rooms, explain which materials and details should carry through the home. Bring the available plans, references, scope and target timeline to the first conversation. The studio can discuss how to develop the brief and the next stage.',links:[{label:'Living-space inspiration',href:'/inspiration/living-spaces'},{label:'Architectural joinery',href:'/services/architectural-joinery'},{label:'Discuss your home',href:'/consultation'}]}
 ],
 '/for-professionals':[
  {title:'A useful brief for the studio',body:'Share the project location, design stage, available plans and elevations, joinery schedule and finish references. Identify the scope you want to discuss, your target programme and any budget parameters. Highlight difficult junctions, access constraints or equipment integration early.'},
  {title:'Keep the design intent clear',body:'Describe the decisions already agreed and the areas that still need development. Drawings, material references and photographs can help explain the intended proportions and details. Nura works across design development, technical detailing, manufacturing and installation; the exact responsibilities should be confirmed for each appointment.'},
  {title:'Connect the brief to relevant work',body:'Explore kitchen and architectural joinery examples, then contact the studio with the drawings and a short explanation of the project. The first discussion is an opportunity to identify the information required, coordination needs and an appropriate next step.',links:[{label:'Kitchen projects',href:'/projects?category=Kitchens'},{label:'Joinery projects',href:'/projects?category=Architectural%20Joinery'},{label:'How the process works',href:'/process'}]}
 ],
 '/process':[
  {title:'1. Explain the brief',body:'Begin with the property location, project scope and the way you want to use the space. Share available drawings, references, an approximate budget and target timeline. These inputs help the studio understand the decisions that matter and the information still required.'},
  {title:'2. Develop the design direction',body:'Layout, materials, storage and specification are considered together. Use the design discussions to clarify priorities and understand the implications of different choices. Agree the scope and next stage with the studio before proceeding.'},
  {title:'3. Resolve technical and delivery requirements',body:'Technical details, manufacturing requirements and installation conditions need to be coordinated for the individual project. Responsibilities, specification, programme and commercial terms should be confirmed with the studio. Timings depend on the scope, chosen materials and project conditions.',links:[{label:'Read our design-process article',href:'/post/our-design-process'},{label:'Prepare for a consultation',href:'/consultation'}]}
 ],
 '/about':[
  {title:'Kitchens and joinery, considered together',body:'Nura Interiors works with private homeowners, architects and interior designers on bespoke kitchens and architectural joinery. Our focus is the relationship between materials, proportion and everyday use: furniture and spaces that belong to the wider architecture of a home.'},
  {title:'From the brief to the detail',body:'A project starts with understanding the space and the priorities of the people who use it. Design direction, material selection and technical detailing bring that brief into focus. The scope of manufacturing, delivery and installation is discussed and confirmed for each project.'},
  {title:'Explore the work and talk to the studio',body:'Browse the project collection and journal to understand different approaches to cabinetry, surfaces, storage and lighting. If you have a kitchen or joinery project in mind, share the location, drawings and intended scope with the studio. We work across London and Dubai.',links:[{label:'Project collection',href:'/projects'},{label:'Nura on LinkedIn',href:'https://www.linkedin.com/company/nura-interiors'},{label:'Contact the studio',href:'/contact'}]}
 ],
 '/consultation':[
  {title:'What to share',body:'Include the property location, the rooms or joinery items involved and the current project stage. Attach available plans and elevations to your email. A few references, an approximate budget and target dates help explain the direction you have in mind.'},
  {title:'Questions to bring',body:'Ask about the information needed to develop the design, the proposed scope of work, material decisions and coordination with your architect or designer. Programme and costs depend on the individual brief and should be confirmed with the studio rather than assumed from another project.'},
  {title:'How to begin',body:'Use the enquiry form or email studio@nura-interiors.com. If you want to speak by telephone, the London contact number is +44 (0)20 7123 6949. Tell us whether the project is in London, Dubai or another location so the relevant requirements can be discussed.',links:[{label:'Send an enquiry',href:'/#contact'},{label:'Our process',href:'/process'}]}
 ],
 '/contact':[
  {title:'Send the studio a useful brief',body:'Tell us the project location, the scope and what you want the space to achieve. Include the current stage, any available drawings and your target timeline. If you know the approximate budget, share it so the conversation can start with the right context.'},
  {title:'Homeowners and design professionals',body:'Private homeowners can use the enquiry form to explain a kitchen or joinery project. Architects and interior designers can email drawings and specifications to the studio. Please arrange any visit directly with the team before travelling.',links:[{label:'Enquiry form',href:'/#contact'},{label:'For architects and designers',href:'/for-professionals'},{label:'London projects',href:'/london'},{label:'Dubai enquiries',href:'/dubai'}]}
 ],
 '/london':[
  {title:'Discuss a kitchen or joinery project in London',body:'Share your London property location, the rooms involved and the project stage with the studio. Available drawings, photographs and material references help explain both practical requirements and design direction. If you are working with an architect or interior designer, include the coordination needs in the brief.'},
  {title:'Explore relevant projects',body:'Browse the kitchen and joinery collection for examples of materials, layouts and details. A previous project is a reference for discussion; the specification, price and programme for your home need to be agreed against its own brief.',links:[{label:'Elm Park Road kitchen',href:'/kitchens/elm-park-road'},{label:'Westover Road joinery',href:'/jointery/westover-road'}]},
  {title:'Contact before visiting',body:'Email studio@nura-interiors.com or call +44 (0)20 7123 6949 to discuss your project and arrange the next step. Confirm the visit details with the team before travelling.',links:[{label:'Prepare for a consultation',href:'/consultation'}]}
 ],
 '/dubai':[
  {title:'Begin with the location and scope',body:'For a Dubai project, tell the studio the property location, project stage and whether the brief includes a kitchen, wardrobes or other fitted joinery. Share the available plans, references and target dates, along with any building access or coordination requirements you already know.'},
  {title:'Confirm the project requirements',body:'Materials, technical details, delivery and installation conditions should be discussed for the individual property. Ask the team to confirm the scope, responsibilities and programme for your project. If your brief involves an architect or designer, include them in the information you share.'},
  {title:'Arrange the first conversation',body:'Email studio@nura-interiors.com with a short description of the Dubai project. Include an approximate budget and drawings where available. Confirm any meeting or visit directly with the studio before travelling.',links:[{label:'Bespoke kitchen services',href:'/services/bespoke-kitchens'},{label:'Architectural joinery',href:'/services/architectural-joinery'},{label:'Send an enquiry',href:'/#contact'}]}
 ]
};
export default function ServiceContent({path}:{path:string}){
 const content=sections[path];if(!content)return null;
 return <div className="service-detail">{content.map(section=><section key={section.title}><h2>{section.title}</h2><p>{section.body}</p>{section.links?<ul>{section.links.map(link=><li key={link.href}><a href={link.href}>{link.label}</a></li>)}</ul>:null}</section>)}</div>;
}
