import {Hero,Photo} from './Editorial';
import EnquiryForm from './EnquiryForm';
import JsonLd from './JsonLd';
import {siteUrl,organization} from '../lib/seo';

export const wardrobeTitle='Bespoke Fitted Wardrobes in London | Nura Interiors';
export const wardrobeDescription='Bespoke fitted wardrobes and dressing rooms designed around your London home. Discuss storage, materials and your brief with Nura’s Fulham studio.';
const reviews=[
 {name:'Natalia Wojda',text:"We couldn't be happier with the work Nura carried out for us."},
 {name:'Florina Trusescu',text:'Visited Nura recently at their newly opened showroom.'},
 {name:'Adam Tariq',text:'What impressed us just as much was the service throughout the project.'}
];
export default function WardrobeLanding(){return <div className="wardrobe-landing">
 <JsonLd data={{'@context':'https://schema.org','@type':'Service',name:'Bespoke wardrobes and dressing rooms',url:siteUrl+'/services/wardrobes-dressing-rooms',provider:{'@id':organization['@id']},areaServed:{'@type':'City',name:'London'},serviceType:'Bespoke fitted wardrobes',description:wardrobeDescription}}/>
 <Hero title="Bespoke fitted wardrobes in London." kicker="Nura / Wardrobes & dressing rooms" asset={{filename:'/assets/archive/58c6cefb8485754a-local.webp',alt:'Fitted timber cabinetry in Nura’s Westover Road joinery project'}} summary="Storage that belongs to your room. A layout that belongs to your life." cta={{href:'#wardrobe-enquiry',label:'Discuss your wardrobe project ↘'}}/>
 <section className="section-pad wardrobe-intro"><p className="eyebrow">Designed around your home</p><h2>A place for everything.<br/><em>Room to be yourself.</em></h2><p>From fitted bedroom wardrobes to dedicated dressing rooms, begin with the way the room needs to work. Nura considers storage, circulation, proportions and material direction together, so the brief responds to both the architecture and the life inside it.</p><a className="button" href="#wardrobe-enquiry">Discuss your wardrobe project ↗</a></section>
 <section className="section-pad wardrobe-options"><p className="eyebrow">Your space, your priorities</p><h2>Make the room work for you.</h2><div className="wardrobe-grid"><article><h3>Fitted wardrobes</h3><p>Plan hanging space, drawers and shelves around your clothes, the room’s proportions and the way you get ready.</p></article><article><h3>Dressing rooms</h3><p>Bring storage and circulation together. Discuss what should be visible, what should be concealed and how the space connects to the bedroom.</p></article><article><h3>Rooms with constraints</h3><p>Share alcoves, ceiling slopes and awkward corners with the studio. The first conversation establishes what is practical for your property.</p></article></div></section>
 <section className="section-pad wardrobe-detail"><figure><Photo asset={{filename:'/assets/archive/a4d6c0bea134eb76-local.webp',alt:'Timber shelving and integrated lighting in Nura’s Westover Road joinery project'}} sizes="(max-width:800px) 100vw, 45vw"/><figcaption>Material and lighting detail from the Westover Road joinery project.</figcaption></figure><div><p className="eyebrow">The detail makes the difference</p><h2>Considered inside.<br/><em>Composed outside.</em></h2><p>Discuss the door finish, internal arrangement, hardware and any lighting requirements together. The material direction should feel at home in the room, while the storage works for everyday use.</p><p>Explore our wider joinery work for an understanding of Nura’s approach to materials and detailing.</p><a className="text-link" href="/joinery/westover-road">See Westover Road joinery ↗</a></div></section>
 <section className="section-pad wardrobe-reviews" aria-labelledby="wardrobe-reviews-title"><p className="eyebrow">Selected Google reviews</p><h2 id="wardrobe-reviews-title">In our clients’ words.</h2><p>Experiences of Nura’s work, service and showroom.</p><div className="wardrobe-grid">{reviews.map(r=><figure key={r.name}><span className="wardrobe-stars" aria-label="5 out of 5 stars">★★★★★</span><blockquote><p>“{r.text}”</p></blockquote><figcaption>{r.name}<small>Google review excerpt</small></figcaption></figure>)}</div><a className="text-link" href="https://www.google.com/maps?cid=4442565278286484644" target="_blank" rel="noopener noreferrer">View Nura on Google ↗</a></section>
 <section className="section-pad wardrobe-plan"><h2>From your brief to a clear next step.</h2><div className="wardrobe-grid"><article><p className="eyebrow">01 / Share</p><h3>Tell us about the room</h3><p>Send your property location, photographs or available plans, storage priorities and any target dates.</p><a className="text-link" href="#wardrobe-enquiry">Send your plans and brief ↗</a></article><article><p className="eyebrow">02 / Discuss</p><h3>Explore the possibilities</h3><p>The studio will review your enquiry and contact you to discuss the brief. Arrange a Fulham showroom visit before travelling.</p><a className="text-link" href="#wardrobe-enquiry">Arrange a Fulham showroom visit ↗</a></article><article><p className="eyebrow">03 / Define</p><h3>Confirm the scope</h3><p>Agree the design requirements, specification, quotation and delivery responsibilities for your individual project.</p></article></div></section>
 <section className="section-pad london-faq"><h2>Before you begin.</h2><details><summary>How much does a bespoke fitted wardrobe cost?</summary><p>The quotation depends on dimensions, materials, internal fittings, finish and site requirements. Share your brief and approximate budget so the studio can discuss the scope. Pricing is confirmed for your project.</p></details><details><summary>How long will design, manufacture and installation take?</summary><p>The programme depends on the agreed specification and project conditions. The studio will discuss timing and confirm the relevant stages before you commit.</p></details><details><summary>Can I visit the showroom?</summary><p>Contact Nura at 367 Fulham Palace Road, London SW6 6TA to arrange your visit and discuss your material direction.</p></details><details><summary>What should I send with my enquiry?</summary><p>Your property location, photographs or plans, an outline of your storage needs and your approximate budget and target dates, if known.</p></details><details><summary>Can fitted wardrobes work in rooms with alcoves, slopes or awkward corners?</summary><p>These constraints should be shared at the first conversation, along with available plans or measurements where possible. The studio can then discuss the information needed to establish what is practical for the property.</p></details><details><summary>Do you design dressing rooms as well as fitted wardrobes?</summary><p>Yes. The service covers fitted bedroom wardrobes and dedicated dressing rooms, with storage, circulation, materials and the relationship to the bedroom considered as part of the brief.</p></details></section>
 <section className="section-pad london-enquiry" id="wardrobe-enquiry" tabIndex={-1} aria-labelledby="wardrobe-enquiry-title"><div><p className="eyebrow">Let’s make room</p><h2 id="wardrobe-enquiry-title">Discuss your<br/><em>wardrobe project.</em></h2><p>Tell us about the room and what you want it to do. The studio will review your enquiry and contact you to discuss the next step.</p><p>367 Fulham Palace Road<br/>London SW6 6TA</p><a href="tel:+442071236949">Call the showroom: 020 7123 6949</a></div><EnquiryForm formLocation="wardrobes"/></section>
 </div>;}
