// Static, trusted markup shared by the preserved homepage overlay and inner pages.
export const footerHtml = `<footer class="site-footer nura-footer">
<div class="nura-footer-intro"><div><a href="/" aria-label="NURA home"><img src="/assets/nura-wordmark.svg" alt="NURA Interiors" width="144" height="54"/></a><p>Bespoke kitchens, cabinetry and whole-home joinery,<br/>designed around the way you live.</p></div><div class="nura-footer-invitation"><p>Tell us about your space.</p><span>Share a few details about your space. Our design team will review your brief and be in touch.</span><a href="/consultation" class="nura-footer-cta" data-nura-enquiry>Discuss your project <span aria-hidden="true">↗</span></a></div></div>
<div class="nura-footer-grid">
<details class="nura-footer-disclosure" open><summary>Explore</summary><nav aria-label="Explore NURA"><a href="/projects">Projects</a><a href="/services">Our services</a><a href="/journal">Journal</a><a href="/inspiration">Inspiration</a><a href="/guides/bespoke-kitchens">Bespoke kitchen guide</a></nav></details>
<details class="nura-footer-disclosure" open><summary>About</summary><nav aria-label="About NURA"><a href="/about">About NURA</a><a href="/process">Our process</a><a href="/sustainability">Sustainability</a></nav><div class="nura-footer-professionals"><h2>For professionals</h2><a href="/for-professionals">For architects &amp; designers</a><a href="/for-professionals">Trade enquiries</a></div></details>
<section aria-labelledby="footer-studios"><h2 id="footer-studios">Studios</h2><a href="/london">London showroom</a><address>367 Fulham Palace Road<br/>London SW6 6TA</address><p class="nura-footer-hours">Monday–Friday: 09:30–18:00<br/>Saturday: 10:00–16:00<br/>Sunday: by prior appointment</p><a class="nura-footer-directions" href="https://www.google.com/maps/search/?api=1&amp;query=367%20Fulham%20Palace%20Road%20London%20SW6%206TA" target="_blank" rel="noopener noreferrer">London directions <span aria-hidden="true">↗</span></a><a href="/dubai">Dubai studio</a><address>Burlington Tower, Marasi Dr<br/>Business Bay, Dubai</address><a class="nura-footer-directions" href="https://www.google.com/maps/search/?api=1&amp;query=Burlington%20Tower%20Marasi%20Dr%20Business%20Bay%20Dubai" target="_blank" rel="noopener noreferrer">Dubai directions <span aria-hidden="true">↗</span></a></section>
<section aria-labelledby="footer-contact"><h2 id="footer-contact">Contact</h2><a href="mailto:studio@nura-interiors.com">studio@nura-interiors.com</a><a href="tel:+442071236949">London: +44 20 7123 6949</a><a href="https://wa.me/971506691090" target="_blank" rel="noopener noreferrer">WhatsApp Dubai: +971 50 669 1090 <span aria-hidden="true">↗</span></a></section>
</div>
<div class="nura-footer-base"><nav class="nura-social-links" aria-label="NURA social media"><a href="https://www.linkedin.com/company/nura-interiors/" target="_blank" rel="noopener noreferrer" aria-label="NURA on LinkedIn"><img src="/assets/linkedin.svg" alt="" width="24" height="24"/>LinkedIn</a><a href="https://www.instagram.com/nura.lnteriors/" target="_blank" rel="noopener noreferrer" aria-label="NURA on Instagram"><img src="/assets/instagram.svg" alt="" width="24" height="24"/>Instagram</a></nav><nav class="nura-footer-legal" aria-label="Legal and privacy"><a href="/privacy-policy">Privacy policy</a><button type="button" data-nura-privacy>Cookie settings</button><a href="/assets/image-license.html">Photography &amp; image licensing</a></nav><small>© 2026 NURA Interiors</small></div>
</footer>`;
