import {notFound} from 'next/navigation';
import {getEntries,type Asset} from '../../lib/content';
import {Hero,Photo,Card,Cta} from '../../components/Editorial';
import type {Metadata} from 'next';
type Props={params:Promise<{slug:string[]}>;searchParams:Promise<{category?:string}>};
export const dynamic='force-dynamic';
const localAsset=(filename:string):Asset=>({filename:'/assets/selected/'+filename,alt:''});
const pageImages:Record<string,string>={'/about':'nura-approach-new.jpg','/process':'nura-process-workshop.webp','/for-professionals':'nura-cta-joinery.jpg','/services/bespoke-kitchens':'elm-park-road.jpg','/services/architectural-joinery':'nura-cta-joinery.jpg','/services/wardrobes-dressing-rooms':'nura-cta-joinery.jpg','/services/living-spaces':'nura-approach-new.jpg','/london':'elm-park-road.jpg','/dubai':'nura-approach-new.jpg','/contact':'nura-hero-shot.jpeg','/consultation':'nura-hero-shot.jpeg'};
const listingTitles:Record<string,string>={'/projects':'Our work.','/journal':'Stories & perspectives.','/services':'Considered interiors.','/inspiration':'Material possibilities.'};
export async function generateMetadata({params}:Props):Promise<Metadata>{const {slug}=await params;const path='/'+slug.join('/');const entry=(await getEntries()).find(x=>x.path===path);return {title:entry?.content.title||listingTitles[path],description:entry?.content.seo_description||entry?.content.summary,alternates:{canonical:path},openGraph:entry?{title:entry.content.title,description:entry.content.seo_description,images:entry.content.hero?.filename?[entry.content.hero.filename]:[]}:undefined};}
function Paragraphs({body}:{body?:string}){return <>{body?.split(/\n\s*\n/).filter(p=>p.trim().length>4).map((p,i)=><p key={i}>{p}</p>)}</>;}
export default async function Page({params,searchParams}:Props){const {slug}=await params;const path='/'+slug.join('/');const entries=await getEntries();const projects=entries.filter(x=>x.content.component==='project').sort((a,b)=>(b.content.source_rank||0)-(a.content.source_rank||0));const entry=entries.find(x=>x.path===path);
 if(listingTitles[path]){const {category}=await searchParams;const items=path==='/projects'?projects.filter(x=>!category||x.content.category===category):path==='/journal'?entries.filter(x=>x.content.component==='article'):path==='/inspiration'?entries.filter(x=>x.content.component==='inspiration'):entries.filter(x=>x.path.startsWith('/services/'));return <main id="main"><Hero title={listingTitles[path]} kicker={'Nura / '+(path==='/projects'?'Collection':path.slice(1))} asset={localAsset(path==='/journal'?'nura-featured-study.jpg':path==='/services'?'nura-cta-joinery.jpg':path==='/inspiration'?'nura-approach-new.jpg':'nura-hero-shot.jpeg')}/><section className="collection section-pad"><div className="section-mark">{path==='/projects'?'Spaces, shaped around life.':path==='/journal'?'Ideas from the studio.':path==='/inspiration'?'Materials, finishes and details.':'Design, detail and delivery.'}</div>{path==='/projects'?<nav className="inner-filters" aria-label="Project categories"><a href="/projects" aria-current={!category?'page':undefined}>All work</a><a href="/projects?category=Kitchens" aria-current={category==='Kitchens'?'page':undefined}>Kitchens</a><a href="/projects?category=Architectural%20Joinery" aria-current={category==='Architectural Joinery'?'page':undefined}>Joinery</a></nav>:null}<div className="inner-project-grid">{items.map((x,i)=><Card key={x.path} entry={pageImages[x.path]?{...x,content:{...x.content,hero:localAsset(pageImages[x.path])}}:x} index={i}/>)}</div></section><Cta/></main>;}
 if(!entry)notFound();const c=entry.content;const hero=pageImages[path]?localAsset(pageImages[path]):c.hero;
 if(c.component==='site_page'){return <main id="main"><Hero title={c.title} kicker="Nura / Considered interiors" asset={hero} summary={c.summary}/><section className="intro section-pad"><div className="section-kicker">{path==='/for-professionals'?'For architects & interior designers':path==='/process'?'From first conversation to final detail':'The Nura approach'}</div><div className="intro-grid"><h2>{path==='/contact'||path==='/consultation'?<>A place<br/><em>to begin.</em></>:path==='/for-professionals'?<>From intent<br/><em>to detail.</em></>:<>Considered<br/><em>from the start.</em></>}</h2><div className="inner-prose"><Paragraphs body={c.body}/><a className="text-link" href={path==='/for-professionals'?'mailto:studio@nura-interiors.com?subject=Professional%20project%20enquiry':'/#contact'}>{path==='/for-professionals'?'Send us your drawings':'Start a conversation'} <span>↗</span></a></div></div></section>{path.startsWith('/services/')?<section className="collection section-pad"><div className="section-heading"><div className="section-mark">Selected work</div><h2>Made for<br/><em>real life.</em></h2><a className="text-link" href="/projects">The collection <span>↗</span></a></div><div className="inner-project-grid">{projects.filter(x=>x.content.category===(path==='/services/bespoke-kitchens'?'Kitchens':'Architectural Joinery')).slice(0,3).map((x,i)=><Card key={x.path} entry={x} index={i}/>)}</div></section>:null}<Cta/></main>;}
 const related=projects.filter(x=>x.path!==path&&x.content.category===c.category).slice(0,3);
 return <main id="main"><Hero title={c.title} kicker={[c.location,c.category].filter(Boolean).join(' · ')} asset={hero}/><section className="intro section-pad"><div className="section-kicker">{c.component==='project'?'Project overview':c.component==='article'?'From the journal':'Inspiration'}</div><div className="intro-grid"><h2>{c.component==='project'?<>Every detail.<br/><em>Considered.</em></>:<>A different<br/><em>perspective.</em></>}</h2><div className="inner-prose"><Paragraphs body={c.body||c.summary}/>{c.specifications?<div className="inner-spec"><p className="eyebrow">Materials & finishes</p><p>{c.specifications}</p></div>:null}</div></div></section>{c.gallery?.length?<section className="inner-gallery section-pad" aria-label={c.title+' photography'}>{c.gallery.map((a,i)=><figure key={a.filename+i} className={i%3===0?'inner-gallery-wide':''}><Photo asset={a} fallbackAlt={c.title+' — photograph '+(i+1)} sizes={i%3===0?'100vw':'(max-width:800px) 100vw, 50vw'}/>{a.caption?<figcaption>{a.caption}</figcaption>:null}</figure>)}</section>:null}{related.length?<section className="collection section-pad"><div className="section-heading"><div className="section-mark">Continue exploring</div><h2>Related<br/><em>spaces.</em></h2><a className="text-link" href="/projects">The collection <span>↗</span></a></div><div className="inner-project-grid">{related.map((x,i)=><Card key={x.path} entry={x} index={i}/>)}</div></section>:null}<Cta/></main>;
}
