import InteractivePortfolio from '../../components/InteractivePortfolio';
import WardrobeLanding,{wardrobeTitle,wardrobeDescription} from '../../components/WardrobeLanding';
import EnquiryForm from '../../components/EnquiryForm';
import LondonLanding from '../../components/LondonLanding';
import {getRelatedArticles} from '../../lib/related-articles';
import ArticleView from '../../components/ArticleView';
import {notFound} from 'next/navigation';
import {getEntries,type Asset} from '../../lib/content';
import {Hero,Photo,Card,Cta} from '../../components/Editorial';
import type {Metadata} from 'next';
import RichArticle from '../../components/RichArticle';
import ServiceContent from '../../components/ServiceContent';
import StudioDetails from '../../components/StudioDetails';
import JsonLd from '../../components/JsonLd';
import {siteUrl,organization,absoluteImage,listingMetadata,articleTitleOverrides} from '../../lib/seo';
type Props={params:Promise<{slug:string[]}>;searchParams:Promise<{category?:string}>};
export const dynamic='force-dynamic';
const localAsset=(filename:string):Asset=>({filename:'/assets/selected/'+filename,alt:''});
const pageImages:Record<string,string>={'/about':'nura-approach-new.jpg','/process':'nura-process-workshop.webp','/for-professionals':'nura-cta-joinery.jpg','/services/bespoke-kitchens':'elm-park-road.jpg','/services/architectural-joinery':'nura-cta-joinery.jpg','/services/wardrobes-dressing-rooms':'nura-cta-joinery.jpg','/services/living-spaces':'nura-approach-new.jpg','/london':'elm-park-road.jpg','/dubai':'nura-approach-new.jpg','/contact':'nura-hero-shot.jpeg','/consultation':'nura-hero-shot.jpeg'};
const listingTitles:Record<string,string>={'/projects':'Our work.','/journal':'Stories & perspectives.','/services':'Considered interiors.','/inspiration':'Material possibilities.'};
export async function generateMetadata({params}:Props):Promise<Metadata>{
 const {slug}=await params;const path='/'+slug.join('/');const entry=(await getEntries()).find(x=>x.path===path);const listing=listingMetadata[path];
 const title=path==='/services/wardrobes-dressing-rooms'?wardrobeTitle:articleTitleOverrides[path]||entry?.content.seo_title||listing?.title||entry?.content.title||'Nura Interiors';
 const description=path==='/services/wardrobes-dressing-rooms'?wardrobeDescription:entry?.content.seo_description||listing?.description||entry?.content.summary||'Explore bespoke kitchens and architectural joinery with Nura Interiors.';
 const image=path==='/services/wardrobes-dressing-rooms'?siteUrl+'/assets/archive/58c6cefb8485754a-local.webp':absoluteImage(entry?.content.hero?.filename)||siteUrl+'/assets/selected/nura-hero-shot.jpeg';
 return {title:{absolute:title},description,alternates:{canonical:path},openGraph:{title,description,url:siteUrl+path,type:entry?.content.component==='article'?'article':'website',images:[image]},twitter:{card:'summary_large_image',title,description,images:[image]}};
}
function PageSchema({path,title,content}:{path:string;title:string;content?:import('../../lib/content').Content}){
 const category=content?.component==='article'?'Journal':content?.component==='inspiration'?'Inspiration':content?.component==='project'||content?.component==='published_project'?'Projects':path.startsWith('/services/')?'Services':undefined;
 const categoryPath=category==='Journal'?'/journal':category==='Inspiration'?'/inspiration':category==='Projects'?'/projects':'/services';
 const items=[{name:'Home',item:siteUrl+'/'},...(category?[{name:category,item:siteUrl+categoryPath}]:[]),{name:title,item:siteUrl+path}];
 const breadcrumbs={'@context':'https://schema.org','@type':'BreadcrumbList',itemListElement:items.map((item,index)=>({'@type':'ListItem',position:index+1,...item}))};
 const article=content?.component==='article'?{'@context':'https://schema.org','@type':'Article','@id':siteUrl+path+'#article',headline:content.title,description:content.seo_description,mainEntityOfPage:siteUrl+path,datePublished:content.published_date,dateModified:content.modified_date||content.published_date,image:absoluteImage(content.hero?.filename),publisher:{'@id':organization['@id']},...(content.author_name?{author:{'@type':'Person',name:content.author_name,...(content.author_name==='Joanne H'?{url:'https://www.linkedin.com/in/joanne-h/',sameAs:['https://www.linkedin.com/in/joanne-h/']}: {})}}:{})}:null;
 return <><JsonLd data={breadcrumbs}/>{article?<JsonLd data={article}/>:null}<nav className="breadcrumbs" aria-label="Breadcrumb">{items.map((item,index)=><span key={item.item}>{index>0?' / ':''}{index===items.length-1?<span aria-current="page">{item.name}</span>:<a href={item.item}>{item.name}</a>}</span>)}</nav></>;
}
function Paragraphs({body}:{body?:string}){return <>{body?.split(/\n\s*\n/).filter(p=>p.trim().length>4).map((p,i)=><p key={i}>{p}</p>)}</>;}
export default async function Page({params,searchParams}:Props){const {slug}=await params;const path='/'+slug.join('/');const entries=await getEntries();const projects=entries.filter(x=>x.content.component==='project').sort((a,b)=>(b.content.source_rank||0)-(a.content.source_rank||0));const entry=entries.find(x=>x.path===path);
 if(listingTitles[path]){const {category}=await searchParams;const items=path==='/projects'?projects.filter(x=>!category||x.content.category===category):path==='/journal'?entries.filter(x=>x.content.component==='article'):path==='/inspiration'?entries.filter(x=>x.content.component==='inspiration'):entries.filter(x=>x.path.startsWith('/services/'));return <main id="main"><PageSchema path={path} title={listingTitles[path]}/><Hero title={listingTitles[path]} kicker={'Nura / '+(path==='/projects'?'Collection':path.slice(1))} asset={localAsset(path==='/journal'?'nura-featured-study.jpg':path==='/services'?'nura-cta-joinery.jpg':path==='/inspiration'?'nura-approach-new.jpg':'nura-hero-shot.jpeg')}/>{path==='/projects'?<InteractivePortfolio/>:null}<section className="collection section-pad"><div className="section-mark">{path==='/projects'?'Spaces, shaped around life.':path==='/journal'?'Ideas from the studio.':path==='/inspiration'?'Materials, finishes and details.':'Design, detail and delivery.'}</div>{path==='/projects'?<nav className="inner-filters" aria-label="Project categories"><a href="/projects" aria-current={!category?'page':undefined}>All work</a><a href="/projects?category=Kitchens" aria-current={category==='Kitchens'?'page':undefined}>Kitchens</a><a href="/projects?category=Architectural%20Joinery" aria-current={category==='Architectural Joinery'?'page':undefined}>Joinery</a></nav>:null}<div className="inner-project-grid">{items.map((x,i)=><Card key={x.path} entry={pageImages[x.path]?{...x,content:{...x.content,hero:localAsset(pageImages[x.path])}}:x} index={i}/>)}</div></section><Cta/></main>;}
 if(!entry)notFound();const c=entry.content;const hero=pageImages[path]?localAsset(pageImages[path]):c.hero;
 if(path==='/consultation')return <main id="main"><PageSchema path={path} title={c.title} content={c}/><Hero title={c.title} kicker="Nura / Your project" asset={hero} summary={c.summary} cta={{href:'#consultation-enquiry',label:'Discuss your project ↘'}}/><section className="section-pad london-enquiry consultation-enquiry" id="consultation-enquiry" tabIndex={-1} aria-labelledby="consultation-enquiry-title"><div><p className="eyebrow">A place to begin</p><h2 id="consultation-enquiry-title">Tell us about<br/><em>your space.</em></h2><p>Share your project location, the rooms you have in mind and where you are in the process. The studio will review your enquiry and contact you to discuss the next step.</p><p>You can include your budget and target dates in the message if you have them. Drawings can be shared by email.</p><a href="mailto:studio@nura-interiors.com">Prefer email? studio@nura-interiors.com</a></div><EnquiryForm formLocation="consultation"/></section><section className="intro section-pad"><div className="inner-prose"><Paragraphs body={c.body}/><ServiceContent path={path}/></div></section><section className="section-pad"><StudioDetails path={path}/></section></main>;
 if(path==='/services/wardrobes-dressing-rooms')return <main id="main"><PageSchema path={path} title="Bespoke fitted wardrobes in London" content={c}/><WardrobeLanding/></main>;
 if(path==='/london')return <main id="main"><PageSchema path={path} title={c.title} content={c}/><Hero title={c.title} kicker="Nura / Fulham, London" asset={hero} summary={c.summary}/><LondonLanding entries={entries}/></main>;
 if(c.component==='site_page'){return <main id="main"><PageSchema path={path} title={c.title} content={c}/><Hero title={c.title} kicker="Nura / Considered interiors" asset={hero} summary={c.summary}/><section className="intro section-pad"><div className="section-kicker">{path==='/for-professionals'?'For architects & interior designers':path==='/process'?'From first conversation to final detail':'The Nura approach'}</div><div className="intro-grid"><h2>{path==='/contact'||path==='/consultation'?<>A place<br/><em>to begin.</em></>:path==='/for-professionals'?<>From intent<br/><em>to detail.</em></>:<>Considered<br/><em>from the start.</em></>}</h2><div className="inner-prose"><Paragraphs body={c.body}/><ServiceContent path={path}/><StudioDetails path={path}/><a className="text-link" href={path==='/for-professionals'?'mailto:studio@nura-interiors.com?subject=Professional%20project%20enquiry':'/#contact'}>{path==='/for-professionals'?'Send us your drawings':'Start a conversation'} <span>↗</span></a></div></div></section>{path.startsWith('/services/')?<section className="collection section-pad"><div className="section-heading"><div className="section-mark">Selected work</div><h2>Made for<br/><em>real life.</em></h2><a className="text-link" href="/projects">The collection <span>↗</span></a></div><div className="inner-project-grid">{projects.filter(x=>x.content.category===(path==='/services/bespoke-kitchens'?'Kitchens':'Architectural Joinery')).slice(0,3).map((x,i)=><Card key={x.path} entry={x} index={i}/>)}</div></section>:null}<Cta/></main>;}
 if(c.component==='article'){const relatedArticles=getRelatedArticles(entry,entries);return <main id="main" className="article-page"><PageSchema path={path} title={c.title} content={c}/><Hero title={c.title} kicker="Nura / Journal" asset={hero}/><ArticleView content={c} related={relatedArticles}/></main>;}
 const related=projects.filter(x=>x.path!==path&&x.content.category===c.category).slice(0,3);
 return <main id="main"><PageSchema path={path} title={c.title} content={c}/><Hero title={c.title} kicker={[c.location,c.category].filter(Boolean).join(' · ')} asset={hero}/><section className="intro section-pad"><div className="section-kicker">{c.component==='project'||c.component==='published_project'?'Project overview':c.component==='article'?'From the journal':'Inspiration'}</div><div className="intro-grid"><h2>{c.component==='project'||c.component==='published_project'?<>Every detail.<br/><em>Considered.</em></>:<>A different<br/><em>perspective.</em></>}</h2><div className="inner-prose"><>{c.component==='article'?<div className="article-meta">{c.author_name?<span>By {c.author_name} &middot; </span>:<span>From the Nura journal &middot; </span>}{c.published_date?<span>Published <time dateTime={c.published_date}>{new Date(c.published_date).toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'})}</time></span>:null}{c.modified_date&&c.modified_date.slice(0,10)!==c.published_date?.slice(0,10)?<span> &middot; Updated <time dateTime={c.modified_date}>{new Date(c.modified_date).toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'})}</time></span>:null}</div>:null}{c.body_nodes?.length?<RichArticle nodes={c.body_nodes}/>:<Paragraphs body={c.body||c.summary}/>}</>{c.specifications?<div className="inner-spec"><p className="eyebrow">Materials & finishes</p><p>{c.specifications}</p></div>:null}</div></div></section>{c.gallery?.length?<section className="inner-gallery section-pad" aria-label={c.title+' photography'}>{c.gallery.map((a,i)=><figure key={a.filename+i} className={i%3===0?'inner-gallery-wide':''}><Photo asset={a} fallbackAlt={c.title+': photograph '+(i+1)} sizes={i%3===0?'100vw':'(max-width:800px) 100vw, 50vw'}/>{a.caption?<figcaption>{a.caption}</figcaption>:null}</figure>)}</section>:null}{related.length?<section className="collection section-pad"><div className="section-heading"><div className="section-mark">Continue exploring</div><h2>Related<br/><em>spaces.</em></h2><a className="text-link" href="/projects">The collection <span>↗</span></a></div><div className="inner-project-grid">{related.map((x,i)=><Card key={x.path} entry={x} index={i}/>)}</div></section>:null}<Cta/></main>;
}
